function Imprimir()  
{  
    document.getElementById("divElem").innerHTML = "<header>" 
        + "<h1><p align='center'>OSCAR <font style='text-transform: uppercase;'>eduardo </font>ORTIZ PINZÓN</p></h1>"
        + "</header>"
    +"<nav>"
    +"<p align='center'>"
    +"    <a href='whoamI.htm'>QUIEN SOY</a>"
    +"    <a href='interes.php'>INTERESES</a>"
    +"    <a href='cv.php'>CURRICULUM VITAE</a>"
    +"    <a href='juego.php'>JUEGO</a>"
    +"</p>"
    +"</nav>"
    +"<section>"
    +"<article>"
    +"<em>"
    +"Soy una persona común y corriente, MÁS corriente que común, voy llevando la vida bien relajada aprendiendo cada día más y mejor"
    +"</em>"
    +"</article>"
    +"</section>"
    +"<aside>"
    +"<div>"
    +"<ol>"
    +"<li><a href='https://www.linkedin.com/oscardo'>LINKEDIN</a></li>"
    +"<li><a href='https://facebook.com/oscardo'>FACEBOOK</a></li>"
    +"<li><a href='https://twitter.com/oscardo'>TWITTER</a></li>"
    +"<li><a href='https://www.youtube.com/channel/UCZww6w1iqDslB2lGoWVPGHQ?view_as=subscriber'>YOUTUBE</a></li>"
    +"<li><a href='https://INSTRAGRAM.com/oscardo'>INSTRAGRAM</a></li>"
    +"<li><a href='https://OSCARDEV.wordpress.com'>BLOG</a></li>"
    +"</ol>"
    +"</div>"
    +"<div>"
    +"<dl>"
    +"<dt>Prioridades</dt><dd>Dios</dd>"
    +"<dt>Prioridades</dt><dd>Colombia</dd>"
    +"<dt>Prioridades</dt><dd>Mi Familia</dd>"
    +"<dt>Prioridades</dt><dd>Mi Novia</dd>"
    +"<dt>Prioridades</dt><dd>Mis Amigos</dd>"
    +"          <dt>Prioridades</dt><dd>Mis conocidos</dd>"
    +"          <dt>Prioridades</dt><dd>Todas las personas</dd>"
    +"          <dt>Prioridades</dt><dd>Mis cervezas</dd>"
    +"      </dl>"
    +"  </div>"
    +"</aside>"
    +"<footer class='pie'>"
    +"Derechos Reservados . 1983 - 2017"
    +"</footer>";  
    //var elem = document.getElementById('divElem');  
    // elem.textContent = dt.toTimeString();  
    //window.setTimeout('ShowTime();', 5000);  
    // "Hello JavaScript!";
}  